
title: "Frank McPherson's Web Notes"
tagline: ""
description: "Follow <a href=\"https://micro.blog/frankm\">@frankm on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/frankm\">@frankm on Micro.blog</a>."
baseurl: ""
url: "https://frankmcpherson.blog"
markdown: "kramdown"
username: "frankm"
microblog_user: "frankm"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Frank McPherson's Web Notes"
name: "Frank McPherson's Web Notes"
gravatar_hash: "734955df329e83c2aa3ffdfec595697d"
avatar: "https://micro.blog/frankm/avatar.jpg"
full_name: "Frank McPherson's Web Notes"
bio: ""
twitter_username: "frankm"
github_username: "fmcpherson"
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"
site_id: "2044"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Frank McPherson"